---
    
- name: "Deploy application on ASG instances"
  become: true
  hosts: all 
  serial: 1
  vars:
    IMAGE_NAME: "{{ image_name}}"
    DOCKERHUB_USERNAME: "{{ dockerhub_username }}"
    DOCKERHUB_TOKEN: "{{ dockerhub_token }}"
    DOMAIN_NAME: "{{ domain_name }}"
    CONTAINER_NAME: "{{ container_name }}" 
    AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}" 
    AWS_ACCESS_KEY: "{{ aws_access_key }}"  
  tasks:
    - name: update the server
      apt: 
        update_cache: yes
    
    - name: ensure dependencies are met
      shell: |
        sudo dpkg --audit
        sudo apt-get update --fix-missing
        sudo apt-get install -f
    
    - name: pull the image
      docker_image:
        name: "{{ IMAGE_NAME }}"
        source: pull

    - name: run the docker container
      docker_container:
        name: "{{ CONTAINER_NAME }}"
        image: "{{ IMAGE_NAME }}"
        state: started
        restart_policy: always
        ports:
          - "3000:3000"

    - name: wait for the container to start
      wait_for:
        host: localhost
        port: 3000
        delay: 5
        timeout: 60
  